// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: crdb/proto/crdb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CRDBService_ProcessStatement_FullMethodName = "/crdb.CRDBService/ProcessStatement"
)

// CRDBServiceClient is the client API for CRDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CRDBServiceClient interface {
	ProcessStatement(ctx context.Context, in *Statement, opts ...grpc.CallOption) (*Ack, error)
}

type cRDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCRDBServiceClient(cc grpc.ClientConnInterface) CRDBServiceClient {
	return &cRDBServiceClient{cc}
}

func (c *cRDBServiceClient) ProcessStatement(ctx context.Context, in *Statement, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CRDBService_ProcessStatement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CRDBServiceServer is the server API for CRDBService service.
// All implementations must embed UnimplementedCRDBServiceServer
// for forward compatibility
type CRDBServiceServer interface {
	ProcessStatement(context.Context, *Statement) (*Ack, error)
	mustEmbedUnimplementedCRDBServiceServer()
}

// UnimplementedCRDBServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCRDBServiceServer struct {
}

func (UnimplementedCRDBServiceServer) ProcessStatement(context.Context, *Statement) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessStatement not implemented")
}
func (UnimplementedCRDBServiceServer) mustEmbedUnimplementedCRDBServiceServer() {}

// UnsafeCRDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CRDBServiceServer will
// result in compilation errors.
type UnsafeCRDBServiceServer interface {
	mustEmbedUnimplementedCRDBServiceServer()
}

func RegisterCRDBServiceServer(s grpc.ServiceRegistrar, srv CRDBServiceServer) {
	s.RegisterService(&CRDBService_ServiceDesc, srv)
}

func _CRDBService_ProcessStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Statement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRDBServiceServer).ProcessStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRDBService_ProcessStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRDBServiceServer).ProcessStatement(ctx, req.(*Statement))
	}
	return interceptor(ctx, in, info, handler)
}

// CRDBService_ServiceDesc is the grpc.ServiceDesc for CRDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CRDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crdb.CRDBService",
	HandlerType: (*CRDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessStatement",
			Handler:    _CRDBService_ProcessStatement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crdb/proto/crdb.proto",
}
